def research_agent(state):

    query = state["query"]
    plan = state["plan"]

    answer = (
        f"Query:\n{query}\n\n"
        f"Plan:\n{plan}\n\n"
        "This is the initial response generated by the Research Agent."
    )

    return {
        "answer": answer
    }